# Generated by Django 6.0.4 on 2026-05-14 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('process', 'В обработке'), ('done', 'Завершена')], default='new', max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('car_model', models.CharField(max_length=100)),
                ('description_problem', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
