# Generated by Django 6.0.4 on 2026-05-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='Service', max_length=150),
            preserve_default=False,
        ),
    ]
