# Generated by Django 6.0.4 on 2026-05-19 06:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_service_user'),
        ('vehicle', '0002_vehicle_owner_alter_vehicle_mileage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_model',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vehicle.vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята'), ('in_progress', 'В работе'), ('waiting_parts', 'Ожидание деталей'), ('done', 'Готово'), ('cancelled', 'Отменено')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='service',
            name='initial_price',
            field=models.DecimalField(decimal_places=2, help_text='Минимальная цена - 500 ₽', max_digits=10, validators=[django.core.validators.MinValueValidator(500.0)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vehicle.vehicle'),
        ),
    ]
