# Generated by Django 6.0.4 on 2026-05-20 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_created_at_alter_service_user'),
        ('vehicle', '0002_vehicle_owner_alter_vehicle_mileage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='vehicle.vehicle'),
        ),
    ]
